# Generated by Django 4.2.6 on 2023-11-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercl',
            name='customer',
        ),
        migrations.AddField(
            model_name='ordercl',
            name='customer_name',
            field=models.CharField(default='Without_Name', max_length=100),
        ),
    ]
