# Generated by Django 4.2.6 on 2023-11-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_remove_ordercl_customer_ordercl_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcl',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
